# Generated by Django 3.2.9 on 2021-11-22 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='food'),
        ),
    ]
