# Generated by Django 3.2.9 on 2021-11-23 22:45

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_food_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, size=[400, 400], upload_to='food'),
        ),
    ]
