# Generated by Django 3.2.9 on 2021-11-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20211123_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='type',
            field=models.CharField(choices=[('AP', 'Appetizer'), ('MN', 'Main'), ('DT', 'Dessert')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
