# Generated by Django 3.2.9 on 2021-11-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_alter_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='course',
            field=models.CharField(choices=[('AP', 'Appetizer'), ('MN', 'Main'), ('DT', 'Dessert')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.CharField(choices=[('VG', 'Vegetarian'), ('GF', 'Gluten-free'), ('BF', 'Beef'), ('CK', 'Chicken'), ('LB', 'Lamb'), ('PG', 'Pig')], max_length=2, null=True),
        ),
    ]
