# Generated by Django 3.2.9 on 2021-11-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_auto_20211125_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='course',
        ),
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.CharField(choices=[('AP', 'Appetizer'), ('MN', 'Main'), ('DT', 'Dessert')], max_length=2, null=True),
        ),
    ]
