# Generated by Django 3.2.9 on 2021-11-29 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_auto_20211125_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='type',
            new_name='course',
        ),
    ]
