# Generated by Django 3.2.9 on 2021-12-02 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_rename_type_food_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='course',
            field=models.CharField(choices=[('AP', 'Appetizer'), ('MN', 'Main'), ('DT', 'Dessert'), ('DR', 'Drink')], max_length=2, null=True),
        ),
    ]
